### ISSUE TITLE
Unable to download live video

### ISSUE THREAD

**Issue by superbonaci** [DmitryScaletta/twitch-dlp#9]
The stream is live right now, but can't be downloaded.
```
$ npx twitch-dlp 'video:geranime4you_40924281333_1722804862' --retry-streams 60 --live-from-start
/home/memetix_/twitch-dlp/twitch-dlp.js:518
  if (!downloadFormat) throw new Error('Wrong format');
                             ^

Error: Wrong format
    at downloadVideo (/home/memetix_/twitch-dlp/twitch-dlp.js:518:30)
    at main (/home/memetix_/twitch-dlp/twitch-dlp.js:680:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v22.5.1
```

similar: https://www.twitch.tv/directory/category/anime-squad

**Comment by DmitryScaletta** [comment]
I think this channel didn't enable "Store past broadcasts" option, so it's not possible to download VODs.

**Comment by DmitryScaletta** [comment]
Updated `DOWNLOAD_PRIVATE_VIDEOS.md` https://github.com/DmitryScaletta/twitch-dlp/commit/18d6a1efff202ac9faf7f0682e67ecbef4d43289
